# Generated by Django 5.1.4 on 2026-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='demo_poster',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
