# Generated by Django 5.1.4 on 2026-01-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_demo_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
