# Generated by Django 5.1.4 on 2026-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='demo_poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
    ]
